# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.roastEdit = QtWidgets.QLineEdit(Dialog)
        self.roastEdit.setObjectName("roastEdit")
        self.verticalLayout.addWidget(self.roastEdit)
        self.typeComboBox = QtWidgets.QComboBox(Dialog)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.verticalLayout.addWidget(self.typeComboBox)
        self.descriptionEdit = QtWidgets.QTextEdit(Dialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout.addWidget(self.descriptionEdit)
        self.priceEdit = QtWidgets.QDoubleSpinBox(Dialog)
        self.priceEdit.setObjectName("priceEdit")
        self.verticalLayout.addWidget(self.priceEdit)
        self.volumeEdit = QtWidgets.QSpinBox(Dialog)
        self.volumeEdit.setObjectName("volumeEdit")
        self.verticalLayout.addWidget(self.volumeEdit)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Coffee"))
        self.typeComboBox.setItemText(0, _translate("Dialog", "Ground"))
        self.typeComboBox.setItemText(1, _translate("Dialog", "Beans"))
        self.saveButton.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
